# Use postgres/example user/password credentials
version: '3.1'

services:
  # Connection string
  # postgresql://postgres:postgres@localhost:5432/db?sslmode=disable
  db:
    image: postgres
    restart: always
    ports: 
        - "5432:5432"
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db

  # http://localhost:8080/?pgsql=db&username=postgres&db=db&ns=public
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080