#cloud-config
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
runcmd:
  - curl -sSLf https://get.k0s.sh | sudo sh
  - sudo k0s install controller --single
power_state:
  mode: reboot
  message: Restarting after installing k0s