create:
	@bash scripts.sh create

stop:
	@bash scripts.sh stop

destroy:
	@bash scripts.sh destroy

show-ip:
	@bash scripts.sh getDropletIP

watch: 
	@air

deploy: 
	@bash scripts.sh deploy

connect:
	@bash scripts.sh connect

service.install:
	@bash scripts.sh service.install

service.restart:
	@bash scripts.sh service.restart 

logs.journal:
	@bash scripts.sh logs.journal

logs.tail:
	@bash scripts.sh logs.journal
